### ISSUE TITLE
esxi安装黑苹果直通核显

### ISSUE THREAD

**Issue by JackHe98** [joyanhui/dev.leiyanhui.com-page#1]
大佬您好，我在你的博客里，看到有个链接，简单安装eaxi黑苹果并且核显直通，但是不知道为什么，链接我点进去打不开，大佬您可以指导我一下，告诉我如何esxi安装黑苹果吗

**Comment by joyanhui** [comment]
黑果 没有那么简单，三言两语说不清。自己研究。

**Comment by JackHe98** [comment]
大佬，可否告知我如何直通核显呢，我琢磨了一个多月，看了好多教程，一无所获。在你这里我看到了一丝希望，可是您的那篇博客文章我无法打开，请您帮帮我好吗，不胜感激！

**Comment by JackHe98** [comment]
> 黑果 没有那么简单，三言两语说不清。自己研究。

大佬，或者您让我可以访问到您那篇简单安装esxi黑苹果的博客文章，我边看边学也是可以的，万分感谢您！
